name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show Folder Structure
        run: ls -R

      - name: Print folder structure
        run: ls -R
      # -------------------------
      # Build React UI
      # -------------------------
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install UI library dependencies
        working-directory: ui/lib
        run: npm install

      - name: Install Web App dependencies
        working-directory: ui/web
        run: npm install

      - name: Build Web App
        working-directory: ui/web
        run: npm run build

      # -------------------------
      # Copy UI build into Spring Boot
      # -------------------------
      - name: Copy UI build to Spring Boot static folder
        run: |
          rm -rf app-services/sports-gateway/src/main/resources/static/*
          cp -r ui/web/dist/* app-services/sports-gateway/src/main/resources/static/

      # -------------------------
      # Build Spring Boot with Gradle
      # -------------------------
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make Gradle executable
        working-directory: app-services
        run: chmod +x gradlew

      - name: Build Spring Boot
        working-directory: app-services
        run: ./gradlew clean build

      # -------------------------
      # Create Deployment Package
      # -------------------------
      - name: Prepare deployment zip
        run: |
          mkdir deploy
          cp app-services/sports-gateway/build/libs/*.jar deploy/application.jar
          cd deploy
          zip -r deploy.zip application.jar

      # -------------------------
      # Deploy to Elastic Beanstalk
      # -------------------------
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: OSDev
          environment_name: OSDev-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy/deploy.zip
